### ISSUE TITLE
Fix Code Coverage

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-server#16]
Coveralls is reporting 100% code coverage which is most definitely **not** true 😜

**Comment by danarth** [comment]
I am not quite sure how to fix this one. I will do some research into how the code coverage works for Node JS, it may do it per file 🤔

**Comment by danarth** [comment]
Just a quick update on this one.

I've identified the problem - it is measuring the 6 lines of code in `test.js` as being covered by the tests in `test.js`.

This is obviously wrong. Going to work on a solution tonight.

**Comment by LoicVerrall** [comment]
You're the best! 👌
