### ISSUE TITLE
Document Code Ownership

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-server#18]
Martin mentioned that it's important to explicitly state _who_ 'owns' the code (in relation to code reviews).

https://matterhorn-presentation.uscs.susx.ac.uk/engage/theodul/ui/core.html?id=fceac7cb-9118-4cfd-b7f1-defb14f8a7a5

**Comment by harrygcollins** [comment]
He did mention that any code created for the project is joint owned by the project. Like if you have a 'work laptop' they usually say anything you create on their laptop is their property. So we could just say any code we create for this is owned by the project?

**Comment by danarth** [comment]
Could this also mean we should document ourselves as authors of different methods javadoc style?

**Comment by LoicVerrall** [comment]
Resolved with #19
