### ISSUE TITLE
Implement Task 4 Functionality

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-server#22]
Implement the server-side of Task 4 (described below). Should accept three parameters from the client:
- Latitude.
- Longitude.
- Radius.

The server should return datapoints around the supplied coordinates (within the radius parameter). A potential enhancement here would be to limit the number of returned datapoints to, say, 40. This will involve averaging some of the datapoints before returning them.

#

[Task description](http://users.sussex.ac.uk/~mfb21/ase/project/task4.html)

The customer is an architect and interested in the development of house prices. The Land Registry is a government department. It was created in 1862 to register the ownership of land and property in England and Wales. As the name indicates, the Land Registry registers the ownership of property. It is one of the largest property databases in Europe. Since 1995, the LR makes ownership data available to the public.

The customer would like a phone app that detects the phone's location and automatically displays Price Paid Data of residential property sales close to the phone's location. The customer could envision some kind of heat map overlay to Google Maps or Open Street map. As the full "Paid Price" database is about 3.5 GBytes big, and doesn't change all that often, it's probably advisable to do some precomputation on the server. Depending on how you implement this task, you might have to covert UK post-code information into latitude/longitude, and the scale of this might cause difficulties. I suggest to address this issue early.

**Comment by harrygcollins** [comment]
Implemented basic functionality with a Node Js Lambda expression in AWS.
