### ISSUE TITLE
Document Task 4 Functionality

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-server#24]
Just a quick one to document the behaviour of the server-side for Task 4. This should include what form the input from the client will take (latitude, longitude, radius) and what form (`JSON`) will be returned to the client.

**Comment by LoicVerrall** [comment]
Discuss how interface-coupled things (e.g. Activities) hard to test

**Comment by Tang-1996** [comment]
Added some bits on 'problems encountered when testing server-side'. Please add anything I've missed.
