### ISSUE TITLE
Refactor code to improve code maintainability

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/MARTIN-server#5]
Code Climate currently gives the Server side code a maintainability grade of C.

We should refactor the code to give us as high grade as possible to reflect good software.

[The Code Climate report is found here!](https://codeclimate.com/github/ASE-ESRS/MARTIN-server)

I've assigned @LoicVerrall and @harrygcollins to this as they have done the server side code up until now, but if anyone else wants to jump on it then go for it!

**Comment by harrygcollins** [comment]
Working on this now
