### ISSUE TITLE
Preprocess Data

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-server#8]
We need to think about what preprocessing we are going to do to the dataset, and how we are going to upload it to AWS.

How are we going to store this data on the server? DynamoDB?

Then we need to document our process.

**Comment by LoicVerrall** [comment]
```
import csv

print 'Opening InputDataset.csv'
inputDataset = open('InputDataset.csv', 'r')
reader = csv.reader(inputDataset)

print 'Opening OutputDataset.csv'
outputDataset = open('OutputDataset.csv', 'w')
writer = csv.writer(outputDataset, delimiter=',')

print 'Extracting postcodes and prices'
for row in reader:
    postcode = row[3]
    price = row[1]

    writer.writerow([postcode, price])

print 'Done'
```

This is a little **Python** script I wrote to extract postcodes and prices from the full dataset. This results is a size reduction from 3.5 GB to 0.35 GB.

The script takes about 45 seconds to run.

**Comment by danarth** [comment]
@LoicVerrall I suppose if we could print out the trimmed down contents of the 3.5GB file into JSON it might fit nicely into a NoSQL database? Just a thought!!!

**Comment by harrygcollins** [comment]
Have you seen the Dynamo DB Javascript web shell?
https://cloudacademy.com/blog/amazon-dynamodb-ten-things/
From what I've read it should be able to handle everything we need It to do so could be worth sticking with it?

**Comment by harrygcollins** [comment]
This looks like a lambda function that will import the CSV data we have into the dynamodb table:
https://github.com/awslabs/data-pipeline-samples/tree/master/samples/DynamoDBImportCSV

**Comment by LoicVerrall** [comment]
Ooo yes! Good find Harry! The indexes mentioned in the first article will be crucial for speed!

**Comment by danarth** [comment]
@LoicVerrall @harrygcollins do you guys think we can close this issue now or not? 😺

**Comment by LoicVerrall** [comment]
Nearly. I want to write a little bit of documentation to the README document for the preprocessing
